### ISSUE TITLE
logo.clj eye rendering can be simplified.

### ISSUE THREAD

**Issue by genmeblog** [nextjournal/clerk-demo#12]
https://github.com/nextjournal/clerk-demo/blob/08cb85f8190b77a7f9d5cc14f68ba8f3872d1c67/notebooks/logo.clj#L69

`doseq` can be simplified to a following snippet:

```clojure
(c2d/path (map (fn [p]
                  (-> (v/sub p (v/vec2 400 400))
                  (complex/sq)
                  (v/mult 0.0015))) hilbert-points))
```

Complex is Vec2.

**Comment by jackrusher** [comment]
Why is this not a PR? 😸

**Comment by genmeblog** [comment]
It will be! I promise! :)
