### ISSUE TITLE
NotDirectoryException on index.md

### ISSUE THREAD

**Issue by rgkirch** [nextjournal/clerk-demo#19]
I opened `dev/user.clj` with emacs and ran `cider-jack-in-clj` then evaled `(clerk/serve! {:watch-paths ["notebooks" "src" "index.md"]})` but got an error about index.md being a file and not a directory.
```
Starting new watcher for paths ["notebooks" "src" "index.md"]
Execution error (NotDirectoryException) at sun.nio.fs.WindowsWatchService$Poller/implRegister (WindowsWatchService.java:379).
index.md
```

**Comment by mk** [comment]
@rgkirch fixed with 23f2848fcd50e3188d9afccecb9e56a47c887973, thanks for the report!
