### ISSUE TITLE
Novice: How to spin up REPL via a cli command

### ISSUE THREAD

**Issue by TheJoeSchr** [nextjournal/clerk-demo#23]
Hi, I love the clerk idea. I'm a novice in clojure, especially unwritten conventions. I read "Brave Clojure" and made a few scripts with `bb` though.   
 
I would love to play around with this interactively, but the `Jack-in` comment doesn't help me. I guess that's an emacs thing. How can I canoncically call this `dev/user.clj` from a terminal? What does an editor to behind the scene to "jack-in"?

I wrote this `bb.edn` to help me, but I don't know, feels wrong? Isn't there a "one-liner" to start a REPL for this kind of situation? 
```clojure
; bb.edn
{:paths ["."]
 :deps {; reuse deps.edn in bb.edn:
               local/deps {:local/root "."} 
        }
 :tasks {; write `.nrepl-port` file on nrepl startup
         nrepl
         {:requires ([babashka.fs :as fs]
                     [babashka.nrepl.server :as srv])
          :task (
do (srv/start-server! {:host "localhost" :port 1339})
                    (spit ".nrepl-port" "1339")
                    (-> (Runtime/getRuntime)
                        (.addShutdownHook
                         (Thread. (fn [] (fs/delete ".nrepl-port")))))
                    (deref (promise)))}}}
```
I use `nvim` with `Conjure` on linux, if that helps/differs.

**Comment by jackrusher** [comment]
You'll need to see the documentation for your Conjure to find out how to evaluate forms interactively. We can't really provide support for tooling that's outside the scope of Clerk.

**Comment by TheJoeSchr** [comment]
Yeah it's "fixed". It's not about how to evaluate interactivily, I know that. I just wrote this so you know what I'm trying to do.

If you read what I wrote you will see it's not in documentation, that's why I asked. Documentation is specific to one editors conventional way of doing things without deeper explanation
