### ISSUE TITLE
some issues

### ISSUE THREAD

**Issue by genmeblog** [nextjournal/clerk-demo#3]
Great to see `clerk` live finally! 

Three small issues at the beginning:

1. (rather harmless) On WSL2 watcher throws an exception, but seems to work:

```
11:50:10.166 [nREPL-session-0c829bc3-2c90-4658-9c85-9546896127b1] DEBUG io.methvin.watcher.DirectoryWatcher - Assuming ExtendedWatchEventModifier.FILE_TREE is not supported
java.lang.UnsupportedOperationException: Modifier not supported
	at java.base/sun.nio.fs.LinuxWatchService$Poller.implRegister(LinuxWatchService.java:238)
	at java.base/sun.nio.fs.AbstractPoller.processRequests(AbstractPoller.java:265)
	at java.base/sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:366)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

2. Unicode chars in the `how_clerk_works.clj` hang my Emacs
3. How to display dataset (from tablecloth) as a table? I managed to display markdown (`(clerk/md (print-str (expand-grid input)))`) but well it's not as cute as the result of the `clerk/table`

**Comment by jackrusher** [comment]
@genmeblog Are these issues still current? If not, could you let us know what subset is? Thanks!

**Comment by genmeblog** [comment]
I think we can close it now.

1. It's still relevant on WSL2 but it's only a information (https://github.com/gmethvin/directory-watcher/blob/master/core/src/main/java/io/methvin/watcher/DirectoryWatcher.java#L390)
2. Now it works, I've changed my emacs config recently and it was something wrong with unicode fonts setup I think.
3. Now I know how to make it (via custom viewer)
