### ISSUE TITLE
data_science example uses missing dataset

### ISSUE THREAD

**Issue by paulbutcher** [nextjournal/clerk-demo#5]
`notebooks/data_science.clj` references `datasets/worker-ceo-ratio.tsv`, which isn't included in this repository (and a quick Google doesn't show it up as an easily available source?).

**Comment by jackrusher** [comment]
Thanks for the report! I'm re-writing that one later today, which will fix this problem :)

**Comment by paulbutcher** [comment]
Great, thanks for the quick response.

Have only just started playing around with Clerk, but very much like what I've seen so far 👍

**Comment by jackrusher** [comment]
Glad to hear you're enjoying it! It'll probably take me another day to finish this data science notebook, but it'll have some very useful examples of pulling from multiple data sources in various formats. :)

**Comment by jackrusher** [comment]
I've pushed a first cut of the data science notebook along with a few more datasets.

**Comment by paulbutcher** [comment]
Had a quick play, and it looks good 👍
